"""add_usage_records

Revision ID: d3469bd9a9c1
Revises: f80228aefd72
Create Date: 2026-06-26 22:08:48.209986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3469bd9a9c1'
down_revision: Union[str, None] = 'f80228aefd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('workflows_started', sa.Integer(), nullable=False),
    sa.Column('workflows_completed', sa.Integer(), nullable=False),
    sa.Column('workflows_failed', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('search_queries', sa.Integer(), nullable=False),
    sa.Column('evidence_fetched', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_date', name='uq_user_period')
    )
    op.create_index(op.f('ix_usage_records_period_date'), 'usage_records', ['period_date'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_period_date'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
