"""add_evidence_feedback

Revision ID: db238a80e0a7
Revises: c147f1c6d406
Create Date: 2026-06-26 14:55:00.893021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db238a80e0a7'
down_revision: Union[str, None] = 'c147f1c6d406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('useful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'user_id', name='uq_evidence_user_feedback')
    )
    op.create_index(op.f('ix_evidence_feedback_evidence_id'), 'evidence_feedback', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_feedback_user_id'), 'evidence_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_feedback_user_id'), table_name='evidence_feedback')
    op.drop_index(op.f('ix_evidence_feedback_evidence_id'), table_name='evidence_feedback')
    op.drop_table('evidence_feedback')
    # ### end Alembic commands ###
