"""add_workflow_mvp_plan

Revision ID: e965ef09b75e
Revises: 15f963db297b
Create Date: 2026-06-28 03:18:20.343923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e965ef09b75e'
down_revision: Union[str, None] = '15f963db297b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('mvp_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'mvp_plan')
    # ### end Alembic commands ###
