"""add_workflows_and_fk_workflow_id

Revision ID: f80228aefd72
Revises: 10ed4bd6a2ea
Create Date: 2026-06-26 21:56:47.502766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80228aefd72'
down_revision: Union[str, None] = '10ed4bd6a2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_created_at'), 'workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.alter_column('agent_runs', 'workflow_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='workflow_id::integer')
    op.create_foreign_key(None, 'agent_runs', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.alter_column('evidence', 'workflow_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='workflow_id::integer')
    op.create_foreign_key(None, 'evidence', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.alter_column('evidence', 'workflow_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.alter_column('agent_runs', 'workflow_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_created_at'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
